Update android.yml
Add Unit Test Reporter action

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -11,10 +11,10 @@ jobs:
 
     runs-on: ubuntu-latest
 
-    steps:
+    steps:    
     - uses: actions/checkout@v4
     - name: set up JDK 17
-      uses: actions/setup-java@v3
+      uses: actions/setup-java@v4
       with:
         java-version: '17'
         distribution: 'temurin'
@@ -24,10 +24,15 @@ jobs:
       run: chmod +x gradlew
     - name: Run Unit Test
       run: ./gradlew testDebugUnitTest
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v4
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/build/test-results/testDebugUnitTest/TEST-*.xml'
     - name: Generate JaCoCo Badge
       uses: cicirello/jacoco-badge-generator@v2
       with:
-        jacoco-csv-file: app/build/reports/jacoco/jacocoTestReportDebug/jacocoTestReportDebug.csv
+        jacoco-csv-file: '**/build/reports/jacoco/jacocoTestReportDebug/jacocoTestReportDebug.csv'
     - name: Build with Gradle
       run: ./gradlew build
     - name: Upload build artifacts
